export const GET_ORDER_LIST_BY_SHOP_REQUEST = "GET_ORDER_LIST_BY_SHOP_REQUEST";
export const GET_ORDER_LIST_BY_SHOP_SUCCESS = "GET_ORDER_LIST_BY_SHOP_SUCCESS";
export const GET_ORDER_LIST_BY_SHOP_FAILURE = "GET_ORDER_LIST_BY_SHOP_FAILURE";

export const GET_ORDER_LIST_BY_USER_REQUEST = "GET_ORDER_LIST_BY_USER_REQUEST";
export const GET_ORDER_LIST_BY_USER_SUCCESS = "GET_ORDER_LIST_BY_USER_SUCCESS";
export const GET_ORDER_LIST_BY_USER_FAILURE = "GET_ORDER_LIST_BY_USER_FAILURE";

export const GET_ORDER_DETAIL_BY_ORDER_ID_REQUEST = "GET_ORDER_DETAIL_BY_ORDER_ID_REQUEST";
export const GET_ORDER_DETAIL_BY_ORDER_ID_SUCCESS = "GET_ORDER_DETAIL_BY_ORDER_ID_SUCCESS";
export const GET_ORDER_DETAIL_BY_ORDER_ID_FAILURE = "GET_ORDER_DETAIL_BY_ORDER_ID_FAILURE";

export const CANCEL_ORDER_BY_ID_REQUEST = "CANCEL_ORDER_BY_ID_REQUEST";
export const CANCEL_ORDER_BY_ID_SUCCESS = "CANCEL_ORDER_BY_ID_SUCCESS";
export const CANCEL_ORDER_BY_ID_FAILURE = "CANCEL_ORDER_BY_ID_FAILURE";

export const GET_ORDER_SHIPPING_STATUS_REQUEST = "GET_ORDER_SHIPPING_STATUS_REQUEST";
export const GET_ORDER_SHIPPING_STATUS_SUCCESS = "GET_ORDER_SHIPPING_STATUS_SUCCESS";
export const GET_ORDER_SHIPPING_STATUS_FAILURE = "GET_ORDER_SHIPPING_STATUS_FAILURE";

export const GET_ORDER_SERVICES_REQUEST = "GET_ORDER_SERVICES_REQUEST";
export const GET_ORDER_SERVICES_SUCCESS = "GET_ORDER_SERVICES_SUCCESS";
export const GET_ORDER_SERVICES_FAILURE = "GET_ORDER_SERVICES_FAILURE";

export const SEND_ORDER_SHIPPING_REQUEST_TO_GHN_REQUEST = "SEND_ORDER_SHIPPING_REQUEST_TO_GHN_REQUEST";
export const SEND_ORDER_SHIPPING_REQUEST_TO_GHN_SUCCESS = "SEND_ORDER_SHIPPING_REQUEST_TO_GHN_SUCCESS";
export const SEND_ORDER_SHIPPING_REQUEST_TO_GHN_FAILURE = "SEND_ORDER_SHIPPING_REQUEST_TO_GHN_FAILURE";